
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LINEA = 6;
  public static final int DIVISION = 15;
  public static final int SUMA = 12;
  public static final int CURVA = 20;
  public static final int MULTI = 14;
  public static final int ANIMAR = 17;
  public static final int COLOR = 16;
  public static final int CUADRADO = 3;
  public static final int OBJETO = 18;
  public static final int GRAFICAR = 2;
  public static final int COMA = 10;
  public static final int EOF = 0;
  public static final int PARENTESIS_C = 8;
  public static final int error = 1;
  public static final int POLIGONO = 7;
  public static final int PARENTESIS_A = 9;
  public static final int CIRCULO = 4;
  public static final int ENTERO = 11;
  public static final int ANTERIOR = 19;
  public static final int RECTANGULO = 5;
  public static final int RESTA = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "GRAFICAR",
  "CUADRADO",
  "CIRCULO",
  "RECTANGULO",
  "LINEA",
  "POLIGONO",
  "PARENTESIS_C",
  "PARENTESIS_A",
  "COMA",
  "ENTERO",
  "SUMA",
  "RESTA",
  "MULTI",
  "DIVISION",
  "COLOR",
  "ANIMAR",
  "OBJETO",
  "ANTERIOR",
  "CURVA"
  };
}

