
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COLOR = 8;
  public static final int COMA = 6;
  public static final int ENTERO = 7;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int CUADRADO = 3;
  public static final int PARENTESIS_C = 4;
  public static final int PARENTESIS_A = 5;
  public static final int GRAFICAR = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "GRAFICAR",
  "CUADRADO",
  "PARENTESIS_C",
  "PARENTESIS_A",
  "COMA",
  "ENTERO",
  "COLOR"
  };
}

